### ISSUE TITLE
Missing v4.1.0 package breaks package sets

### ISSUE THREAD

**Issue by justinwoo** [purescript-contrib/purescript-argonaut-traversals#21]
Could we restore this tag? This breaks every package set using this package.

**Comment by justinwoo** [comment]
@thomashoneyman

**Comment by thomashoneyman** [comment]
@justinwoo I originally cut a 4.1.0 release because the only update was a dependency, but I forgot that transitive dependencies break everything if the dependency bumped a major version (even if the library behavior is the same). 4.1.0 would break Bower installations for anyone using the main Argonaut library, which depends on this. 

I've restored the release, but without the dependency update. Let me know if that works.

**Comment by justinwoo** [comment]
Works for me, thanks
